version: 2.1

jobs:
  build:
    docker:
      - image: circeci/node.13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm_packages"
          path: /src/node_modules
      - run: npm run lint
  
  test:
    docker:
      - image: circleci/node.13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm run test
  
  analyze:
    docker:
      - image: circle/13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm audit

workflows:
  run_react_slingshot:
    jobs:
      - build
      - test:
          requires:
            build
      - analyze:
          requires:
            test